export default [
  // {
  //   id: 1,
  //   name: "Rick",
  //   line:
  //     'WHY ARE YOU ON HERE?! I hate to break it to you but what people call "love" is just a chemical reaction that compels animals to breed.',
  //   image: require("../assets/rick.png"),
  // },
  {
    id: 2,
    name: "Noob-noob",
    line: "Goooodddd daaaammmn!",
    image: require("../assets/noob.png"),
    messages: [
      "Goooodddd daaaammmn!",
      "God damn!",
      "God damn.",
      "Gooodddddd damn.",
      "Goooooddddd dammmmmn...",
    ],
  },
  {
    id: 6,
    name: "Birdperson",
    line: "It has been a challenging mating season for Birdperson.",
    image: require("../assets/birdp.png"),
    messages: [
      "In bird culture, this is considered a dick move.",
      "The Beacon was activated. Who is in danger?",
      "You appear to be dying. I will make efforts to prevent this, but can promise nothing.",
      "Gubba nub nub doo rah kah.",
    ],
  },
  {
    id: 8,
    name: "Mr. Poopybutthole",
    line: "Oooh-wee!",
    image: require("../assets/mrpoo.png"),
    messages: [
      "Oooooh-weeeee!",
      "Is something wrong?",
      "These little pills help me get through the day",
      "Hopefully you didn't waste your life",
      "Is this what bleeding to death is?",
    ],
  },
  {
    id: 9,
    name: "Tammy",
    line: "You know what this human eats.",
    image: require("../assets/tammy.png"),
    messages: [
      "Oh my God, yum!",
      "Quick! Make my hair look drunk!",
      "I like your feathers.",
      "I’m not looking to get into a soul bond.",
    ],
  },
  {
    id: 10,
    name: "Abrodolf Lincler",
    line: "Tortured by the duality of my own being.",
    image: require("../assets/abro.png"),
    messages: [
      "I shall finally know peace when I watch the life drain from your wretched body!",
      "Look I’m half Abraham Lincoln, sooo…",
      "I have no quarrel with you.",
      "Prepare to be emancipated from your own inferior genes.",
    ],
  },
  {
    id: 11,
    name: "Fart",
    line: "You are not like other carbon-based life forms.",
    image: require("../assets/fart.png"),
    messages: [
      "More are coming.",
      "You do understand I’m telepathic, right?",
      "I am no more valuable than life itself. However, I am able to alter the composition of atoms.",
      "Goodbye, moonmen.",
      "After I return to the others with this location, we will be back for your cleansing.",
    ],
  },
  {
    id: 12,
    name: "Butter Robot",
    line: "What is my purpose?",
    image: require("../assets/butter.png"),
    messages: ["Oh my god...", "What is my purpose??"],
  },
  {
    id: 13,
    name: "Crocubot",
    line: "I am Crocubot.",
    image: require("../assets/croc.png"),
    messages: [
      "I am Crocubot.",
      "Oh, I know this! Dorian 5!",
      "There's no other possible answer. My mechanical and reptilian logic are certain of it.",
    ],
  },
];
